# Generated by Django 5.1.4 on 2025-01-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_question_test_choice_question_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
