# Generated by Django 5.1.4 on 2025-01-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_question_correct_answer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="user",
        ),
    ]
