# Generated by Django 5.1.4 on 2025-01-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_lesson_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="language",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
