# Generated by Django 5.1.4 on 2025-01-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_test_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="language",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
